### PR TITLE
expose constructors

### PR DESCRIPTION
**Pull request by delaneyj**
Need the ability to create `ecs.Entity` for querying for external resources (networking layer in this case).

### CODE REVIEW

**Comment by mlange-42** [comment]
I don't think that it should be possible to create any entities at all, except for the zero entity.

In case you want to transmit entities over a network and can't do so directly, entities support serialization to and deserialization from JSON (as 2-element int array). Although this can be abused to create entities, its purpose is only serialization and deserialization (e.g. as in [arche-serde](https://github.com/mlange-42/arche-serde)).

**Comment by delaneyj** [comment]
Ok, this is a non-starter unfortunately.  Have to go a different route

**Comment by mlange-42** [comment]
Maybe you want to explain a bit more detailed what you want to do?

**Comment by mlange-42** [comment]
Closing as stale.

**Pull request closed without merging**
